"""include email verification

Revision ID: 10d848f2762c
Revises: de1d79add814
Create Date: 2026-06-23 17:20:51.834022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10d848f2762c'
down_revision: Union[str, Sequence[str], None] = 'de1d79add814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_partner', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('seller', sa.Column('email_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller', 'email_verified')
    op.drop_column('delivery_partner', 'email_verified')
    # ### end Alembic commands ###
