"""adding the delivery_partner table

Revision ID: 5e6cfe551506
Revises: 636df3338569
Create Date: 2026-06-09 20:57:55.585643

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e6cfe551506'
down_revision: Union[str, Sequence[str], None] = '636df3338569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_partner',
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dlv_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('serviceable_zip_codes', sa.ARRAY(sa.INTEGER()), nullable=True),
    sa.Column('max_handling_capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('dlv_id')
    )
    op.create_index(op.f('ix_delivery_partner_dlv_id'), 'delivery_partner', ['dlv_id'], unique=False)
    op.create_index(op.f('ix_delivery_partner_email'), 'delivery_partner', ['email'], unique=True)
    op.create_index(op.f('ix_delivery_partner_user_name'), 'delivery_partner', ['user_name'], unique=True)
    op.add_column('shipment', sa.Column('del_partner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'shipment', 'delivery_partner', ['del_partner_id'], ['dlv_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipment', type_='foreignkey')
    op.drop_column('shipment', 'del_partner_id')
    op.drop_index(op.f('ix_delivery_partner_user_name'), table_name='delivery_partner')
    op.drop_index(op.f('ix_delivery_partner_email'), table_name='delivery_partner')
    op.drop_index(op.f('ix_delivery_partner_dlv_id'), table_name='delivery_partner')
    op.drop_table('delivery_partner')
    # ### end Alembic commands ###
