"""new table added

Revision ID: cf6f6006d281
Revises: 1a9ae97fc4fa
Create Date: 2026-06-17 10:11:00.983057

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf6f6006d281'
down_revision: Union[str, Sequence[str], None] = '1a9ae97fc4fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='TBD'))
    op.add_column('seller', sa.Column('zip_code', sa.Integer(), nullable=False, server_default='00'))
    op.drop_column('shipment', 'status')
    op.add_column('shipment_event', sa.Column('status', sa.Enum('PLACED', 'IN_TRANSIT', 'OUT_OF_DELIVERY', 'DELIVERED', name='shipmentstatus'), nullable=False))
    op.add_column('shipment_event', sa.Column('location', sa.Integer(), nullable=False))
    op.add_column('shipment_event', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('shipment_event', sa.Column('shipment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'shipment_event', 'shipment', ['shipment_id'], ['ship_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipment_event', type_='foreignkey')
    op.drop_column('shipment_event', 'shipment_id')
    op.drop_column('shipment_event', 'description')
    op.drop_column('shipment_event', 'location')
    op.drop_column('shipment_event', 'status')
    op.add_column('shipment', sa.Column('status', postgresql.ENUM('PLACED', 'IN_TRANSIT', 'OUT_OF_DELIVERY', 'DELIVERED', name='shipmentstatus'), autoincrement=False, nullable=False))
    op.drop_column('seller', 'zip_code')
    op.drop_column('seller', 'address')
    # ### end Alembic commands ###
