data = [
    {"id": 1, "title": "Think Python",
     "author": "Allen B. Downey",
     "publisher": "O'Reilly Media",
     "published_date": "2021-01-01",
     "page_count": 1234,
     "language": "English"
     },
    {"id": 2, "title": "Clean Code",
     "author": "Robert C. Martin",
     "publisher": "Prentice Hall",
     "published_date": "2008-08-01",
     "page_count": 464, "language": "Spanish"
     },
    {"id": 3, "title": "The Pragmatic Programmer", "author": "David Thomas", "publisher": "Addison-Wesley",
     "published_date": "2019-09-13", "page_count": 352, "language": "French"},
    {"id": 4, "title": "Introduction to Algorithms", "author": "Thomas H. Cormen", "publisher": "MIT Press",
     "published_date": "2009-07-31", "page_count": 1312, "language": "German"},
    {"id": 5, "title": "Fluent Python", "author": "Luciano Ramalho", "publisher": "O'Reilly Media",
     "published_date": "2021-08-17", "page_count": 992, "language": "Chinese"},
    {"id": 6, "title": "Python Crash Course", "author": "Eric Matthes", "publisher": "No Starch Press",
     "published_date": "2019-05-03", "page_count": 544, "language": "Japanese"},
    {"id": 7, "title": "Automate the Boring Stuff with Python", "author": "Al Sweigart", "publisher": "No Starch Press",
     "published_date": "2019-11-14", "page_count": 592, "language": "Arabic"},
    {"id": 8, "title": "Design Patterns", "author": "Erich Gamma", "publisher": "Addison-Wesley",
     "published_date": "1994-10-31", "page_count": 416, "language": "Hindi"},
    {"id": 9, "title": "You Don't Know JS", "author": "Kyle Simpson", "publisher": "O'Reilly Media",
     "published_date": "2019-12-17", "page_count": 264, "language": "Russian"},
    {"id": 10, "title": "Eloquent JavaScript", "author": "Marijn Haverbeke", "publisher": "No Starch Press",
     "published_date": "2018-12-04", "page_count": 472, "language": "Portuguese"},
    {"id": 11, "title": "Learning Python", "author": "Mark Lutz", "publisher": "O'Reilly Media",
     "published_date": "2013-07-06", "page_count": 1648, "language": "Italian"},
    {"id": 12, "title": "Head First Python", "author": "Paul Barry", "publisher": "O'Reilly Media",
     "published_date": "2016-11-25", "page_count": 624, "language": "Korean"},
    {"id": 13, "title": "Effective Python", "author": "Brett Slatkin", "publisher": "Addison-Wesley",
     "published_date": "2019-11-15", "page_count": 496, "language": "Dutch"},
    {"id": 14, "title": "Python for Data Analysis", "author": "Wes McKinney", "publisher": "O'Reilly Media",
     "published_date": "2022-09-27", "page_count": 600, "language": "Swedish"},
    {"id": 15, "title": "The Linux Programming Interface", "author": "Michael Kerrisk", "publisher": "No Starch Press",
     "published_date": "2010-10-22", "page_count": 1552, "language": "Polish"},
    {"id": 16, "title": "Refactoring", "author": "Martin Fowler", "publisher": "Addison-Wesley",
     "published_date": "2018-11-30", "page_count": 448, "language": "Turkish"},
    {"id": 17, "title": "The Clean Coder", "author": "Robert C. Martin", "publisher": "Prentice Hall",
     "published_date": "2011-05-13", "page_count": 256, "language": "Greek"},
    {"id": 18, "title": "Code Complete", "author": "Steve McConnell", "publisher": "Microsoft Press",
     "published_date": "2004-06-09", "page_count": 960, "language": "Hebrew"},
    {"id": 19, "title": "Structure and Interpretation of Computer Programs", "author": "Harold Abelson",
     "publisher": "MIT Press", "published_date": "1996-07-25", "page_count": 688, "language": "Thai"},
    {"id": 20, "title": "Programming in Python 3", "author": "Mark Summerfield", "publisher": "Addison-Wesley",
     "published_date": "2010-12-10", "page_count": 648, "language": "Vietnamese"},
    {"id": 21, "title": "Dive Into Python 3", "author": "Mark Pilgrim", "publisher": "Apress",
     "published_date": "2009-10-22", "page_count": 400, "language": "English"},
    {"id": 22, "title": "Python Cookbook", "author": "David Beazley", "publisher": "O'Reilly Media",
     "published_date": "2013-05-10", "page_count": 706, "language": "Spanish"},
    {"id": 23, "title": "Python Pocket Reference", "author": "Mark Lutz", "publisher": "O'Reilly Media",
     "published_date": "2014-01-21", "page_count": 248, "language": "French"},
    {"id": 24, "title": "Think Java", "author": "Allen B. Downey", "publisher": "O'Reilly Media",
     "published_date": "2020-01-16", "page_count": 468, "language": "German"},
    {"id": 25, "title": "Think C++", "author": "Allen B. Downey", "publisher": "O'Reilly Media",
     "published_date": "2019-06-13", "page_count": 392, "language": "Chinese"},
    {"id": 26, "title": "Think Data Structures", "author": "Allen B. Downey", "publisher": "O'Reilly Media",
     "published_date": "2021-10-15", "page_count": 226, "language": "Japanese"},
    {"id": 27, "title": "Grokking Algorithms", "author": "Aditya Bhargava", "publisher": "Manning Publications",
     "published_date": "2016-05-01", "page_count": 256, "language": "Arabic"},
    {"id": 28, "title": "Cracking the Coding Interview", "author": "Gayle Laakmann McDowell", "publisher": "CareerCup",
     "published_date": "2015-07-01", "page_count": 708, "language": "Hindi"},
    {"id": 29, "title": "The Algorithm Design Manual", "author": "Steven S. Skiena", "publisher": "Springer",
     "published_date": "2020-09-15", "page_count": 800, "language": "Russian"},
    {"id": 30, "title": "Artificial Intelligence: A Modern Approach", "author": "Stuart Russell",
     "publisher": "Pearson", "published_date": "2020-05-05", "page_count": 1152, "language": "Portuguese"},
    {"id": 31, "title": "Deep Learning", "author": "Ian Goodfellow", "publisher": "MIT Press",
     "published_date": "2016-11-18", "page_count": 800, "language": "Italian"},
    {"id": 32, "title": "Hands-On Machine Learning with Scikit-Learn", "author": "Aurélien Géron",
     "publisher": "O'Reilly Media", "published_date": "2022-10-25", "page_count": 856, "language": "Korean"},
    {"id": 33, "title": "Pattern Recognition and Machine Learning", "author": "Christopher Bishop",
     "publisher": "Springer", "published_date": "2006-08-17", "page_count": 738, "language": "Dutch"},
    {"id": 34, "title": "The Art of Computer Programming", "author": "Donald Knuth", "publisher": "Addison-Wesley",
     "published_date": "1997-05-04", "page_count": 672, "language": "Swedish"},
    {"id": 35, "title": "Introduction to the Theory of Computation", "author": "Michael Sipser",
     "publisher": "Cengage Learning", "published_date": "2012-06-27", "page_count": 504, "language": "Polish"},
    {"id": 36, "title": "Operating System Concepts", "author": "Abraham Silberschatz", "publisher": "Wiley",
     "published_date": "2018-01-23", "page_count": 1024, "language": "Turkish"},
    {"id": 37, "title": "Database System Concepts", "author": "Abraham Silberschatz", "publisher": "McGraw-Hill",
     "published_date": "2010-01-12", "page_count": 1376, "language": "Greek"},
    {"id": 38, "title": "Computer Networking: A Top-Down Approach", "author": "James Kurose", "publisher": "Pearson",
     "published_date": "2016-05-06", "page_count": 864, "language": "Hebrew"},
    {"id": 39, "title": "Modern Operating Systems", "author": "Andrew Tanenbaum", "publisher": "Pearson",
     "published_date": "2014-03-20", "page_count": 1104, "language": "Thai"},
    {"id": 40, "title": "Compilers: Principles, Techniques, and Tools", "author": "Alfred V. Aho",
     "publisher": "Addison-Wesley", "published_date": "2006-08-31", "page_count": 1008, "language": "Vietnamese"},
    {"id": 41, "title": "Computer Organization and Design", "author": "David Patterson", "publisher": "Morgan Kaufmann",
     "published_date": "2016-04-15", "page_count": 704, "language": "English"},
    {"id": 42, "title": "JavaScript: The Good Parts", "author": "Douglas Crockford", "publisher": "O'Reilly Media",
     "published_date": "2008-05-01", "page_count": 176, "language": "Spanish"},
    {"id": 43, "title": "Python Machine Learning", "author": "Sebastian Raschka", "publisher": "Packt Publishing",
     "published_date": "2015-09-23", "page_count": 454, "language": "French"},
    {"id": 44, "title": "Data Science from Scratch", "author": "Joel Grus", "publisher": "O'Reilly Media",
     "published_date": "2019-04-16", "page_count": 406, "language": "German"},
    {"id": 45, "title": "The Hundred-Page Machine Learning Book", "author": "Andriy Burkov",
     "publisher": "Andriy Burkov", "published_date": "2019-01-13", "page_count": 160, "language": "Chinese"},
    {"id": 46, "title": "Interpretable Machine Learning", "author": "Christoph Molnar", "publisher": "Lulu.com",
     "published_date": "2020-03-15", "page_count": 320, "language": "Japanese"},
    {"id": 47, "title": "Foundations of Machine Learning", "author": "Mehryar Mohri", "publisher": "MIT Press",
     "published_date": "2018-01-19", "page_count": 504, "language": "Arabic"},
    {"id": 48, "title": "Machine Learning: A Probabilistic Perspective", "author": "Kevin Murphy",
     "publisher": "MIT Press", "published_date": "2012-08-24", "page_count": 1104, "language": "Hindi"},
    {"id": 49, "title": "Bayesian Reasoning and Machine Learning", "author": "David Barber",
     "publisher": "Cambridge University Press", "published_date": "2012-05-10", "page_count": 736,
     "language": "Russian"},
    {"id": 50, "title": "Probabilistic Machine Learning", "author": "Kevin Murphy", "publisher": "MIT Press",
     "published_date": "2022-03-01", "page_count": 1568, "language": "Portuguese"}
]
